# Generated by Django 5.2.17 on 2026-09-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_exerciseentry_coop_group_id_exerciseentry_logged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='provider',
            field=models.CharField(choices=[('fitbit', 'Fitbit'), ('withings', 'Withings')], max_length=32),
        ),
        migrations.AlterField(
            model_name='rawingest',
            name='source',
            field=models.CharField(choices=[('phone', 'Phone sync'), ('fitbit', 'Fitbit API'), ('withings', 'Withings API'), ('import', 'File import')], db_index=True, max_length=16),
        ),
    ]
