# Generated by Django 5.2.17 on 2026-08-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_partner_logging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discoverable_by_username',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_code',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
    ]
