from __future__ import annotations

from datetime import datetime
from uuid import UUID

from ninja import Schema


class FitnessPlaylistOut(Schema):
    key: str
    title: str
    source_label: str
    logged_as: str
    exercise_count: int


class FitnessExerciseOut(Schema):
    video_id: str
    title: str
    duration_s: int


class FitnessPlaylistDetailOut(Schema):
    key: str
    title: str
    source_label: str
    logged_as: str
    exercises: list[FitnessExerciseOut]


class FitnessCompleteIn(Schema):
    video_name: str
    duration_s: int
    #: Friends who did this clip alongside you. Each gets their own entry.
    partner_ids: list[UUID] = []
    #: One id per press of Complete, generated by the client. Ties the rows
    #: together and lets a retried request be recognised as the same session.
    coop_group_id: UUID | None = None


class FitnessStatsOut(Schema):
    minutes_today: int
    completed_today: int


class FitnessPartnerOut(Schema):
    """A friend the player may tick. `SocialUserOut`'s fields, by design.

    Kept as its own class only because the OpenAPI component map is keyed by
    class name and this app's schemas must be prefixed `Fitness*`.
    """

    id: UUID
    username: str
    avatar_url: str | None = None
    #: False when the friend has turned off shared workouts. Rendered greyed
    #: out rather than hidden: a name silently missing reads as a bug.
    accepts_partner_logging: bool


class FitnessSessionOut(Schema):
    id: UUID
    video_name: str
    duration_s: int
    occurred_at: datetime
    #: The username of whoever pressed Complete, when that was not the owner
    #: of this entry. None for a solo session.
    logged_by: str | None = None
